import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

// Read the package.json to get the version
const pkgPath = join(rootDir, 'node_modules', '@nostr-dev-kit', 'cache-sqlite-wasm', 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
const version = pkg.version;

// Copy the worker with version in filename
const workerSource = join(rootDir, 'node_modules', '@nostr-dev-kit', 'cache-sqlite-wasm', 'dist', 'worker.js');
const workerDest = join(rootDir, 'static', `worker-${version}.js`);

mkdirSync(join(rootDir, 'static'), { recursive: true });

const content = readFileSync(workerSource, 'utf-8');
writeFileSync(workerDest, content);

// Create a TypeScript file with the version constant
const versionTsContent = `// Auto-generated by scripts/copy-worker.js - DO NOT EDIT
export const CACHE_WORKER_VERSION = '${version}';
`;
writeFileSync(join(rootDir, 'src', 'lib', 'worker-version.ts'), versionTsContent);

console.log(`✅ Copied worker.js to worker-${version}.js`);
console.log(`✅ Created worker-version.ts with version ${version}`);
